#spring.application.name=journalApp
#
#spring.data.mongodb.uri = mongodb+srv://iamarpit369_db_user:WUuQXz7QQtHMkrMV@cluster0.kw42spo.mongodb.net/?appName=Cluster0
#spring.data.mongodb.database = journaldb
#spring.data.mongodb.auto-index-creation=true